---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhsso-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tosin2013/servicenow-ocp-service.git
    targetRevision: main
    path: kustomize/rhsso/operator/overlays/stable
  destination:
    server: https://kubernetes.default.svc
    namespace: sso
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
