---
# ansible/roles/aap_configuration/tasks/setup_job_template.yml

- name: Create ServiceNow Execution Environment
  ansible.controller.execution_environment:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ controller_validate_certs | default(false) }}"
    name: "ServiceNow OpenShift EE"
    image: "quay.io/takinosh/servicenow-ocp-ee:latest"
    organization: "Default"
    state: present

- name: Create OpenShift Project Creation Job Template
  ansible.controller.job_template:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: "{{ controller_validate_certs | default(false) }}"
    name: "OpenShift Project Creation"
    description: "Creates an OpenShift project based on a ServiceNow request."
    project: "ServiceNow OpenShift Integration"
    playbook: "ansible/servicenow_project_creation.yml"
    inventory: "Default Inventory"
    execution_environment: "ServiceNow OpenShift EE"
    credentials:
      - "OpenShift API Token"
      - "ServiceNow-OpenShift Vault"
    extra_vars:
      rhsso_url: "{{ rhsso_url }}"
      vault_keycloak_password: "{{ vault_keycloak_password }}"
      keycloak_admin_username: "admin"
      servicenow_realm: "servicenow"
      team_members: "{{ team_members | default('[]') }}"
      keycloak_admin_password: "{{ keycloak_admin_password | default(vault_keycloak_password) }}"
      default_email_domain: "{{ default_email_domain | default('example.com') }}"
    survey_enabled: true
    survey_spec:
      name: ""
      description: ""
      spec:
        - variable: project_name
          question_name: "Project Name"
          type: "text"
          required: true
        - variable: display_name
          question_name: "Display Name"
          type: "text"
          required: true
        - variable: description
          question_name: "Description"
          type: "textarea"
          required: false
        - variable: requestor
          question_name: "Requestor"
          type: "text"
          required: true
        - variable: keycloak_admin_password
          question_name: "Keycloak Admin Password (leave blank to use vault_keycloak_password)"
          type: "password"
          required: false
        - variable: default_email_domain
          question_name: "Default Email Domain"
          type: "text"
          required: false
          default: "example.com"
        - variable: team_members
          question_name: "Team Members (JSON array, e.g. [\"bob\", \"carol\"])"
          type: "textarea"
          required: false
          default: "[]"
        - variable: servicenow_request_number
          question_name: "ServiceNow Request Number"
          type: "text"
          required: true
        - variable: environment
          question_name: "Environment"
          type: "text"
          required: false
          default: "development"
        - variable: team
          question_name: "Team"
          type: "text"
          required: false
          default: "default"
        - variable: manage_keycloak_users
          question_name: "Create Keycloak Users"
          type: "multiplechoice"
          required: false
          default: "true"
          choices:
            - "true"
            - "false"
        - variable: requestor_email
          question_name: "Requestor Email"
          type: "text"
          required: false
        - variable: requestor_first_name
          question_name: "Requestor First Name"
          type: "text"
          required: false
        - variable: requestor_last_name
          question_name: "Requestor Last Name"
          type: "text"
          required: false
        - variable: temp_password
          question_name: "Temporary Password"
          type: "password"
          required: false
          default: "TempPass123!"
    state: present
