---
# ansible/roles/aap_configuration/tasks/setup_project.yml

- name: Create Git Project in AAP
  ansible.controller.project:
    name: "ServiceNow OpenShift Integration"
    organization: "Default"
    scm_type: "git"
    scm_url: "https://github.com/tosin2013/servicenow-ocp-service.git"
    scm_branch: "main"
    scm_update_on_launch: true
    state: present
