---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aap


resources:
  - ../../base
patches:
  - path: patch-channel.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: ansible-automation-platform
      namespace: aap
