# GitHub Dependabot configuration for ServiceNow OpenShift Service
# Automatically manages dependencies and security updates

version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "tosin2013"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Python dependencies in execution environment
  - package-ecosystem: "pip"
    directory: "/execution-environment/files"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "tosin2013"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Allow both direct and indirect dependency updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Node.js dependencies (if any package.json files exist)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "tosin2013"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/execution-environment"
    schedule:
      interval: "daily"  # Check daily for Red Hat security updates
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "tosin2013"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Allow both direct and indirect updates for security patches
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
