# 02-eso-role.yaml
# Defines a set of permissions (the "what") within a specific namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secretstore-reader-role
  namespace: external-secrets-operator
rules:
  # Rule for core secret access
  - apiGroups: [""] # The core API group
    resources: ["secrets"]
    verbs:
      - "get"
      - "list"
      - "watch"
  # Rule for the mandatory self-permission check
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectrulesreviews"]
    verbs:
      - "create"
