apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: external-secrets-operator
subjects:
- kind: ServiceAccount
  name: secretstore-sa
  namespace: external-secrets-operator
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
