apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: ansible
  namespace: aap
spec:
  controller:
    disabled: false
  eda:
    disabled: true
  hub:
    disabled: false
    file_storage_size: 100Gi
    file_storage_storage_class: ocs-storagecluster-cephfs
    storage_type: file
  image_pull_policy: IfNotPresent
  lightspeed:
    disabled: true
  no_log: true
  redis_mode: standalone
  route_tls_termination_mechanism: Edge