---
# Detailed ServiceNow Flow Designer Validation
- name: Detailed Flow Designer Validation
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/production.yml
  
  tasks:
    - name: Get all Flow Designer workflows
      uri:
        url: "{{ servicenow_url }}/api/now/table/sys_hub_flow?sysparm_fields=name,description,active,created_on"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Accept: "application/json"
        validate_certs: false
      register: all_flows
      failed_when: false

    - name: Display Flow Details
      debug:
        msg:
          - "🎉 ServiceNow Flow Designer Implementation Complete!"
          - "=================================================="
          - ""
          - "📊 Deployed Workflows ({{ all_flows.json.result | length }} total):"
          - "{% for flow in all_flows.json.result %}"
          - "  ✅ {{ flow.name }}"
          - "     Status: {{ 'Active' if flow.active == 'true' else 'Inactive' }}"
          - "     Created: {{ flow.created_on }}"
          - "{% if flow.description %}     Description: {{ flow.description }}{% endif %}"
          - ""
          - "{% endfor %}"
          - "🚀 Implementation Status: COMPLETE"
          - "🔗 Access Flow Designer: {{ servicenow_url }}/nav_to.do?uri=flow_designer.do"
