apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: rhsso
  namespace: sso
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    gitops.test/pipeline-verification: "2025-09-06-test"
  labels:
    app: sso
    app.kubernetes.io/instance: rhsso-instance
spec:
  instances: 1
  profile: RHSSO
  externalAccess:
    enabled: true
