---
# Check OpenShift Catalog Variables
- name: Check OpenShift Catalog Variables
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
    - servicenow_integration_vars.yml

  vars:
    sn_host: "{{ servicenow_instance_url }}"
    sn_username: "{{ servicenow_admin_user }}"
    sn_password: "{{ vault_servicenow_admin_password }}"
    basic_catalog_item_id: "1a3b56b1470cfa50292cc82f316d4378"

  tasks:
    - name: Get OpenShift catalog variables only
      uri:
        url: "{{ sn_host }}/api/now/table/item_option_new"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: form-urlencoded
        body:
          sysparm_query: "cat_item={{ basic_catalog_item_id }}"
          sysparm_fields: "sys_id,name,question_text,type,reference,mandatory,order"
        status_code: 200
        return_content: yes
      register: openshift_variables

    - name: Display OpenShift variables
      debug:
        msg: |
          OpenShift Catalog Variables:
          {% for var in openshift_variables.json.result %}
          - Name: {{ var.name }}
          - Question: {{ var.question_text }}
          - Type: {{ var.type }}
          - Reference: {{ var.reference }}
          - Mandatory: {{ var.mandatory }}
          - Order: {{ var.order }}
          - Sys ID: {{ var.sys_id }}
          ---
          {% endfor %}

    - name: Check if our variables exist
      debug:
        msg: |
          Expected Variables Check:
          {% set expected_vars = ['project_name', 'display_name', 'environment', 'requestor_first_name', 'requestor_last_name', 'team_members', 'business_justification'] %}
          {% for expected in expected_vars %}
          {% set found = openshift_variables.json.result | selectattr('name', 'equalto', expected) | list %}
          - {{ expected }}: {{ 'FOUND' if found else 'MISSING' }}
          {% endfor %}

    - name: Show catalog item details
      uri:
        url: "{{ sn_host }}/api/now/table/sc_cat_item/{{ basic_catalog_item_id }}"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        status_code: 200
        return_content: yes
      register: catalog_item_details

    - name: Display catalog item info
      debug:
        msg: |
          Catalog Item Details:
          - Name: {{ catalog_item_details.json.result.name }}
          - Short Description: {{ catalog_item_details.json.result.short_description }}
          - Active: {{ catalog_item_details.json.result.active }}
          - Sys ID: {{ catalog_item_details.json.result.sys_id }}
