---
# Fix ServiceNow Catalog Item Fulfillment Automation Level
- name: Update Catalog Items for Full Automation
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
    - servicenow_integration_vars.yml

  vars:
    sn_host: "{{ servicenow_instance_url }}"
    sn_username: "{{ servicenow_admin_user }}"
    sn_password: "{{ vault_servicenow_admin_password }}"
    basic_catalog_item_id: "1a3b56b1470cfa50292cc82f316d4378"
    database_catalog_item_id: "aa3b1e75470cfa50292cc82f316d43e2"

  tasks:
    - name: Update Basic OpenShift Project Request - Set Fully Automated
      uri:
        url: "{{ sn_host }}/api/now/table/sc_cat_item/{{ basic_catalog_item_id }}"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
        method: PATCH
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        body:
          fulfillment_automation_level: "fully_automated"
          workflow: ""  # Clear any manual workflow
          flow_designer_flow: ""  # Clear any flow designer workflows
          delivery_plan: ""  # Clear delivery plan that might require manual steps
        status_code: 200
        return_content: yes
      register: basic_item_update

    - name: Update Database OpenShift Project Request - Set Fully Automated  
      uri:
        url: "{{ sn_host }}/api/now/table/sc_cat_item/{{ database_catalog_item_id }}"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
        method: PATCH
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        body:
          fulfillment_automation_level: "fully_automated"
          workflow: ""  # Clear any manual workflow
          flow_designer_flow: ""  # Clear any flow designer workflows
          delivery_plan: ""  # Clear delivery plan that might require manual steps
        status_code: 200
        return_content: yes
      register: database_item_update

    - name: Create Fulfillment Automation Workflow (Optional Enhancement)
      uri:
        url: "{{ sn_host }}/api/now/table/wf_workflow"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
        method: POST
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        body:
          name: "OpenShift Project Auto-Fulfillment"
          table: "sc_req_item"
          condition: "cat_item={{ basic_catalog_item_id }}^ORcat_item={{ database_catalog_item_id }}"
          active: true
          description: "Automatic fulfillment workflow for OpenShift project requests"
        status_code: 201
        return_content: yes
      register: workflow_creation
      ignore_errors: yes

    - name: Verify Catalog Item Updates
      uri:
        url: "{{ sn_host }}/api/now/table/sc_cat_item"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: form-urlencoded
        body:
          sysparm_query: "sys_id={{ basic_catalog_item_id }}^ORsys_id={{ database_catalog_item_id }}"
          sysparm_fields: "name,fulfillment_automation_level,workflow,flow_designer_flow,delivery_plan"
        status_code: 200
        return_content: yes
      register: verification_result

    - name: Display fulfillment automation fix results
      debug:
        msg: |
          🎯 Catalog Item Fulfillment Automation Fixed!
          
          ✅ Updates Applied:
          1. Basic OpenShift Project Request ({{ basic_catalog_item_id }})
             - Fulfillment automation level: fully_automated
             - Manual workflows: cleared
             - Delivery plans: cleared
          
          2. Database OpenShift Project Request ({{ database_catalog_item_id }})
             - Fulfillment automation level: fully_automated  
             - Manual workflows: cleared
             - Delivery plans: cleared
          
          🔍 Verification Results:
          {% for item in verification_result.json.result %}
          - {{ item.name }}: {{ item.fulfillment_automation_level }}
          {% endfor %}
          
          🎯 What This Enables:
          ✅ Automatic state transitions (Requested → In Process → Work in Progress)
          ✅ Business rules trigger at correct state changes
          ✅ No manual approval required for fulfillment
          ✅ True end-to-end automation
          
          🚀 Next Steps:
          1. Submit a new ServiceNow request
          2. Watch automatic state progression
          3. Business rules should trigger AAP automatically
          4. Complete hands-off workflow!
          
          ⚠️ Note: Existing requests may still require manual state changes,
          but NEW requests will be fully automated!
