---
# Fix Catalog Variables - Ensure they're string type, not reference
- name: Fix ServiceNow Catalog Variables
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
    - servicenow_integration_vars.yml

  vars:
    sn_host: "{{ servicenow_instance_url }}"
    sn_username: "{{ servicenow_admin_user }}"
    sn_password: "{{ vault_servicenow_admin_password }}"
    basic_catalog_item_id: "1a3b56b1470cfa50292cc82f316d4378"

  tasks:
    - name: Get current catalog variables
      uri:
        url: "{{ sn_host }}/api/now/table/item_option_new"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: form-urlencoded
        body:
          sysparm_query: "cat_item={{ basic_catalog_item_id }}"
        status_code: 200
        return_content: yes
      register: current_variables

    - name: Display current variables
      debug:
        msg: |
          Current Catalog Variables:
          {% for var in current_variables.json.result %}
          - Name: {{ var.name }}
          - Type: {{ var.type }}
          - Question: {{ var.question_text }}
          - Sys ID: {{ var.sys_id }}
          {% endfor %}

    - name: Fix Project Name variable type
      uri:
        url: "{{ sn_host }}/api/now/table/item_option_new"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
        method: PUT
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        body:
          type: "string"
          reference: ""
        status_code: 200
        return_content: yes
      register: fix_project_name
      vars:
        project_name_var: "{{ current_variables.json.result | selectattr('name', 'equalto', 'project_name') | first }}"
      when: project_name_var is defined
      loop: "{{ current_variables.json.result }}"
      loop_control:
        loop_var: var
      when: var.name == "project_name" and var.type != "string"

    - name: Fix all string variables to ensure proper type
      uri:
        url: "{{ sn_host }}/api/now/table/item_option_new/{{ var.sys_id }}"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
        method: PUT
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        body:
          type: "string"
          reference: ""
          reference_qual: ""
        status_code: 200
        return_content: yes
      register: fix_variables
      loop: "{{ current_variables.json.result }}"
      loop_control:
        loop_var: var
      when: 
        - var.name in ['project_name', 'display_name', 'requestor_first_name', 'requestor_last_name', 'team_members', 'business_justification']
        - var.type != "string"

    - name: Display fix results
      debug:
        msg: |
          Variable Fix Results:
          {% for result in fix_variables.results %}
          {% if not result.skipped %}
          - Fixed: {{ result.var.name }} - Now type: string
          {% endif %}
          {% endfor %}
