---
# Simple ServiceNow Flow Designer Validation
- name: Validate Flow Designer Implementation
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/production.yml
  
  tasks:
    - name: Test ServiceNow API Access
      uri:
        url: "{{ servicenow_url }}/api/now/table/sys_hub_flow"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Accept: "application/json"
        validate_certs: false
      register: api_test
      failed_when: false

    - name: Check for Flow Designer workflows
      uri:
        url: "{{ servicenow_url }}/api/now/table/sys_hub_flow?sysparm_query=nameLIKEKeycloak^ORnameLIKEOpenShift"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Accept: "application/json"
        validate_certs: false
      register: flow_search
      failed_when: false

    - name: Display Flow Designer Status
      debug:
        msg:
          - "🔍 ServiceNow Flow Designer Validation"
          - "======================================"
          - "API Access: {{ 'SUCCESS' if api_test.status == 200 else 'FAILED (' + (api_test.status|string) + ')' }}"
          - "Flow API Response: {{ api_test.status | default('N/A') }}"
          - "Flows Found: {{ flow_search.json.result | length if flow_search.json is defined else 0 }}"
          - ""
          - "🎯 Implementation Status:"
          - "{{ '✅ Flow Designer COMPLETE - Workflows are deployed!' if (flow_search.json is defined and flow_search.json.result | length > 0) else '❌ Flow Designer NOT COMPLETE - No workflows found' }}"
