---
# Test RBAC Configuration Playbook
- name: Test RBAC Group Mappings
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
    - openshift_oidc_vars.yml
  
  tasks:
    - name: Create cluster admin group binding
      kubernetes.core.k8s:
        api_version: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        name: "oidc-cluster-admins"
        definition:
          metadata:
            name: "oidc-cluster-admins"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: Group
              name: "cluster-admins"
            - apiGroup: rbac.authorization.k8s.io
              kind: Group
              name: "openshift-admins"
        state: present
        validate_certs: false
        host: "{{ ocp_api_url }}"
        api_key: "{{ vault_openshift_token }}"
      register: cluster_admin_binding

    - name: Create developer group binding
      kubernetes.core.k8s:
        api_version: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        name: "oidc-developers"
        definition:
          metadata:
            name: "oidc-developers"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: edit
          subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: Group
              name: "developers"
            - apiGroup: rbac.authorization.k8s.io
              kind: Group
              name: "dev-team"
        state: present
        validate_certs: false
        host: "{{ ocp_api_url }}"
        api_key: "{{ vault_openshift_token }}"
      register: developer_binding

    - name: Create viewer group binding
      kubernetes.core.k8s:
        api_version: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        name: "oidc-viewers"
        definition:
          metadata:
            name: "oidc-viewers"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: view
          subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: Group
              name: "viewers"
            - apiGroup: rbac.authorization.k8s.io
              kind: Group
              name: "read-only"
        state: present
        validate_certs: false
        host: "{{ ocp_api_url }}"
        api_key: "{{ vault_openshift_token }}"
      register: viewer_binding

    - name: Display RBAC configuration results
      debug:
        msg:
          - "RBAC Group Mappings Configuration:"
          - "Cluster Admin Binding: {{ 'Success' if cluster_admin_binding.changed else 'Already exists' }}"
          - "Developer Binding: {{ 'Success' if developer_binding.changed else 'Already exists' }}"
          - "Viewer Binding: {{ 'Success' if viewer_binding.changed else 'Already exists' }}"
